config/routes.rb
WGTool::Application.routes.draw do

	match '/users/search' => 'users#search'
  resources :articles
	resources :users
  resources :invoices
  match "/auth/:provider/callback" => "sessions#create"
  post "/users/:id/mail" => "users#mail_info"
  match '/users/:id/feed' => 'users#feed', :as => :feed, :defaults => { :format => 'atom' }
  match "/signout" => "sessions#destroy", :as => :signout
  match '/:action' => 'application##{:action}'

   root :to => 'application#home'

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	belongs_to :creator, :class_name => "User"
	has_many :duties
	has_many :users, :through => :duties

	validates :comment, :price, :presence => true

	def individual_sum
		price / duties.count
	end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.order('created_at DESC').all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invoices }
    end
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invoice }
    end
  end

  # GET /invoices/new
  # GET /invoices/new.json
  def new
    @invoice = Invoice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invoice }
    end
  end

  # GET /invoices/1/edit
  def edit
    @invoice = Invoice.find(params[:id])
  end

  # POST /invoices
  # POST /invoices.json
  def create
    user_ids = params[:invoice][:userids].split(',')
    params[:invoice].delete :userids
    params[:invoice][:price] = params[:invoice][:price].gsub(/\,/, "." )
    @invoice = Invoice.new(params[:invoice])

    if user_ids.empty?
      flash[:error] = "Please enter asscociated users"
      render action: "new"
      return
    end
    @invoice.creator = current_user

    respond_to do |format|
      if @invoice.save
        # create duties
        user_ids.each do |user_id|
          user = User.find(user_id)
          Duty.create!(:invoice => @invoice, :user => user)
        end
        mail_errors = send_mails(:created)
        if mail_errors
          flash[:error] = "Error while sending mail notifications: contact admin"
        end
        format.html { redirect_to @invoice, :flash => { success: 'Invoice was successfully created.' } }
        format.json { render json: @invoice, status: :created, location: @invoice }
      else
        format.html { render action: "new" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /invoices/1
  # PUT /invoices/1.json
  def update
    @invoice = Invoice.find(params[:id])
    if current_user != @invoice.creator
      redirect_to :root, :error => "Du darfst nur deine eigenen Rechnungen bearbeiten."
      return
    end

    user_ids = params[:invoice][:userids].split(',').collect { |id_str| id_str.to_i}
    params[:invoice].delete :userids
    params[:invoice][:price] = params[:invoice][:price].gsub(/\,/, "." )

    if user_ids.empty?
      render action: "edit", notice: 'No users given'
      return
    end

    respond_to do |format|
      if @invoice.update_attributes(params[:invoice])
        # find duties to remove
        to_remove = Duty.where(:invoice_id => @invoice.id).all.reject { |duty| user_ids.include? duty.user_id }
        Duty.delete(to_remove.collect { |r| r.id })
        # find or add remaining
        user_ids.each do |user_id|
          duty = Duty.find_or_create_by_invoice_id_and_user_id(@invoice.id, user_id)
        end
        mail_errors = send_mails(:updated)
        if mail_errors
          flash[:error] = "Error while sending mail notifications: contact admin"
        end
        format.html { redirect_to @invoice, :flash => { success: 'Invoice was successfully updated.'} }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to invoices_url }
      format.json { head :ok }
    end
  end


  private
  def send_mails(type)
    errors = false
    @invoice.users.each do |user|
      if user.wants_mail && user.email != ''
        begin
          case type
          when :created
            UserMailer.invoice_created(user, @invoice).deliver
          when :updated
            UserMailer.invoice_updated(user, @invoice).deliver
        end
        rescue Exception
          puts $!, $@
          errors |= true
        end
      end
    end
    return errors
  end

end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :comment, :class => "label" %><br />
    <%= f.text_area :comment %>

    <%= f.label :price, :class => "label" %><br />
    <%= f.text_field :price %>

    <%= f.label :date, :class => "label" %><br />
    <%= f.date_select :date %>

    <%= f.label :userids, :class => "label" %><br />
    <div class="clearfix">
      <div class="input">
        <%= text_field_tag 'invoice[userids]' %>
      </div>
    </div>

  <div class="actions">
    <%= f.submit :class => "btn primary" %>
    <%= link_to 'Cancel', invoices_path, :class => "btn" %>
  </div>

  <% 
    if @invoice.users.empty?
      user_ids = ""
    else
      user_ids = @invoice.users.collect { |u| "{id:"+h(u.id.to_s)+", name:\""+h(u.name)+"\"}" } .join(",").html_safe
    end
  %>
  <script type="text/javascript">
  $(document).ready(function() {
    $("#invoice_userids").tokenInput("/users/search", {
      prePopulate: [
        <%= user_ids %>
      ], 
      theme: "facebook"
    }); 
  });
  </script>

app/views/invoices/_invoice.html.erb
<div class="invoice row well">
<% if current_user && current_user == invoice.creator %>
  <%= link_to 'x', invoice, confirm: 'Wirklich löschen?', method: :delete, :title => 'Eintrag löschen', :class => 'close' %>
  <%= link_to 'Bearbeiten', edit_invoice_path(invoice), :class => 'edit' %>
<% end %>

<div style="display:table;" class="span5">
	<div class="span1 center-cell">
		<%= link_to invoice.creator.name, user_path(invoice.creator), :class => "btn btn-success" %>
	</div>
	<div class="span1 center-cell">
		<div style="height:50%; border-bottom: 5px solid #EEEEEE; margin: 0 5px;">
		</div>
	</div>
	<div class="span1 center-cell">
		<span class="label label-important text-center"><%= euro invoice.price %></span> 
	</div>
	<div class="span1 center-cell">
		<div style="height:50%; border-bottom: 5px solid #EEEEEE; margin-left: 5px;">
		</div>
	</div>
	<div class="span2 center-cell">
	  <blockquote id="duty-users">
		<% invoice.duties.each do |duty| %>
			<%= link_to duty.user.name, user_path(duty.user), :class => "btn" %><br/>
		<% end %>
		 </blockquote>
	</div>
</div>

<div class="span5">
  <p><small><%= l invoice.date, :format => :long %></small></p>
  <blockquote>
 	 <p class="span7"><%= simple_format invoice.comment %></p>
  </blockquote>
</div>

</div>

app/views/invoices/edit.html.erb
<h1>Editing invoice</h1>

<%= bootstrap_form_for :invoice, :url => {:action =>  :update}, :method => 'PUT', :html => { :class => :form } do |f| %>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<h1>Alle Rechnungen</h1>

<p><%= link_to 'Neue Rechnung', new_invoice_path, :class => 'btn btn-primary' %></p>

<%= render @invoices %>

app/views/invoices/new.html.erb
<h1>New invoice</h1>

<%= bootstrap_form_for :invoice, :url => invoices_path, :html => { :class => :form } do |f| %>
  <%= render :partial => "form", :locals => {:f => f}  %>
<% end %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">

<div style="display:table;" class="span5">
	<div class="span1 center-cell">
		<%= link_to @invoice.creator.name, user_path(@invoice.creator), :class => "btn success" %>
	</div>
	<div class="span1 center-cell">
		<div style="height:50%; border-bottom: 5px solid #EEEEEE; margin: 0 5px;">
		</div>
	</div>
	<div class="span1 center-cell">
		<span class="label important"><%= euro @invoice.price %></span> 
	</div>
	<div class="span1 center-cell">
		<div style="height:50%; border-bottom: 5px solid #EEEEEE; margin-left: 5px;">
		</div>
	</div>
	<div class="span2 center-cell">
	  <blockquote id="duty-users">
		<% @invoice.duties.each do |duty| %>
			<%= link_to duty.user.name, user_path(duty.user), :class => "btn" %><br/>
		<% end %>
		 </blockquote>
	</div>
</div>

<div class="span5">
  <p><small><%= l @invoice.date, :format => :long %></small></p>
  <blockquote>
 	 <p class="span7"><%= @invoice.comment %></p>
  </blockquote>
</div>

</div>

<%= link_to 'Edit', edit_invoice_path(@invoice) %>