config/routes.rb
WGTool::Application.routes.draw do

	match '/users/search' => 'users#search'
  resources :articles
	resources :users
  resources :invoices
  match "/auth/:provider/callback" => "sessions#create"
  post "/users/:id/mail" => "users#mail_info"
  match '/users/:id/feed' => 'users#feed', :as => :feed, :defaults => { :format => 'atom' }
  match "/signout" => "sessions#destroy", :as => :signout
  match '/:action' => 'application##{:action}'

   root :to => 'application#home'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :own_invoices, :class_name => "Invoice", :foreign_key => 'creator_id'
	has_many :duties
	has_many :invoices, :through => :duties

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"].split(" ").first
      user.wants_mail = false;
    end
  end

  def standing
    minus = invoices.reduce(0) do |sum, val|
      sum - val.individual_sum
    end
    own_invoices.reduce(minus) do |sum, val|
      sum + val.price
    end
  end

  def mentioned_invoices
    own = own_invoices.order('date DESC').limit(10)
    other = invoices.order('date DESC').limit(10)
    ( ((own-other) + other).sort { |a,b| b.created_at <=> a.created_at } )[0..10]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, :only => [:feed]

  def search
    @users = User.where('lower(name) LIKE ?', "#{params[:q].downcase}%")

    respond_to do |format|
      format.html { render json: @users, :only => [:id, :name] }
      format.json { render json: @users, :only => [:id, :name] }
    end
  end

  def mail_info
    @user = User.find(params[:id])
    @user.email = params[:email]
    @user.wants_mail = params[:wants_mail] ? true : false;
    @user.save
    redirect_to @user, :flash => { success: 'E-Mail Daten gespeichert.' }
  end

  def feed
    @user = User.find(params[:id])
    @title = "W9Tool"
    @invoices = @user.mentioned_invoices
    @updated = @invoices.first.updated_at
    respond_to do |format|
      format.atom { render :layout => false }
      # we want the RSS feed to redirect permanently to the ATOM feed
      format.rss { redirect_to feed_path(:format => :atom), :status => :moved_permanently }
    end
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])
    @users = User.all
    @invoices = @user.mentioned_invoices
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :flash => { success: 'User was successfully created.' }}
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :flash => { success: 'User was successfully updated.' }}
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
    <%= f.label :name, t("activerecord.attributes.user.name", :default => "Name"), :class => :label %>
    <%= f.text_field :name, :class => 'text_field' %>


<div class="actions">
  <button class="btn primary" type="submit">Save</button> or
	<%= link_to "Cancel", users_path %>
</div>

app/views/users/edit.html.erb
<%= bootstrap_form_for :user, :url => users_path, :html => { :class => :form } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/users/index.html.erb
<table class="zebra-striped">
 <thead>
  <tr>
    <th>ID</th>
    <th>
      <%= t("activerecord.attributes.user.name", :default => t("activerecord.labels.name", :default => "Name")) %>
    </th>
    <th></th>
    <th>Email</th>
    <th>Created at</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| -%>
   <tr>
    <td><%= user.id %></td>
    <td><%= link_to user.name, user_path(user) %></td>
    <td><%= user.wants_mail ? 'x' : '' %></td>
    <td><%= user.email %></td>
    <td><%= user.created_at %></td>
    <td>
      <%= link_to "Show", user_path(user) %>
      <%= link_to "Edit", edit_user_path(user) %>
      <%= link_to "Destroy", user_path(user), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
    </td>
    </tr>
    <% end -%>
   </tbody>
</table>

<%= link_to "New", new_user_path, :class => 'btn primary' %>

app/views/users/new.html.erb
<h1>Signup</h1>
<p>
<%= bootstrap_form_for :user, :url => users_path, :html => { :class => :form } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>
</p>

app/views/users/show.html.erb
<% content_for :head do %>
  <%= auto_discovery_link_tag(:atom, {:action => "feed"}, {:title => "W9-Tool"}) %>
<% end %>

<h1>
	<%= @user.name[0] %><small><%= @user.name[1..-1] %></small>
	<%= link_to 'Neue Rechnung', new_invoice_path, :class => 'btn btn-primary', :style => 'float: right' %>
	<%= link_to '', '#', :id => 'mail-btn', :class => 'btn icon-envelope', :style => 'float: right', :title => 'Notification Settings' %>
	<%= link_to '', { :action => "feed" }, :class => 'btn icon-info-sign', :style => 'float: right', :title => 'ATOM Feed' %>
</h1>
<div id="mail-box">
	<%= form_tag(:controller => "users", :action => "mail_info", :method => "post") do %>
		<div class="well">
			<label class="checkbox" style="width:210px; padding-right: 10px;">
				<%= check_box_tag 'wants_mail', 'Receive Mail?', @user.wants_mail %>
				Bei neuen Rechnungen Mail an:
			</label>
			<div class="input-prepend">
				<span class="add-on">@</span>
				<input class="span4" type="text" size="16" name="email" value="<%= @user.email %>">
				<button class="btn btn-success" type="submit" style="float:right; ;padding: 4px;">Speichern</button>
			</div>
		</div>
	<% end %>
</div>

<% @users.each do |user| %>
	<% label_class = user.standing == 0 ? 'label' : (user.standing > 0 ? 'label-success' : 'label-important') %>
	<span style="padding: 20px;">
		<%= user.name %>
		<span class="label <%= label_class %>">
			<%= euro user.standing %>
		</span>
	</span>
<% end %>

<div id="chart" style="width: 500px; height: 200px; margin: 3px auto"></div>

<script type="text/javascript">
var standings = [
<% @users.each do |user| %>
	{
		name : '<%= user.name %>',
		data: [<%= user.standing %>]
	}<%= ',' unless user==@users.last %>
<% end %>
];
</script>

<%= render :partial => 'invoices/invoice', :collection => @invoices %>