config/routes.rb
WGTool::Application.routes.draw do

	match '/users/search' => 'users#search'
  resources :articles
	resources :users
  resources :invoices
  match "/auth/:provider/callback" => "sessions#create"
  post "/users/:id/mail" => "users#mail_info"
  match '/users/:id/feed' => 'users#feed', :as => :feed, :defaults => { :format => 'atom' }
  match "/signout" => "sessions#destroy", :as => :signout
  match '/:action' => 'application##{:action}'

   root :to => 'application#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WG-Tool</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <a href="/" class="brand">W9Tool</a>
        <ul class="nav">
          <% if current_user %>
            <li><%= link_to "Rechnungen", invoices_path  %></li>
            <li><%= link_to "Statistiken", :controller => "application", :action => "stats" %></li>
            <li><%= link_to "Einkaufsliste", articles_path %></li>
          <% end %>
        </ul>
        <ul class="nav pull-right">
          <% if current_user %>
            <li><%= link_to "Logout", signout_path %></li>
          <% end %>
          <li><%= link_to "About", :controller => "application", :action => "about"  %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="content">
      <%- flash.each do |key, msg| -%>
        <div class="span6 alert <%= 'alert-' + key.to_s %>">
          <button class="close" data-dismiss="alert">×</button>
          <%= msg %>
        </div>
      <%- end -%>
      <div class="row">
        <div class="span12">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</body>
</html>